export const GET_USERINFO = 'GET_USERINFO';
export const GET_USERAGENT = 'GET_USERAGENT';
export const GET_NETWORKTYPE = 'GET_NETWORKTYPE';
export const SAVE_SPLASH_STATUS = 'SAVE_SPLASH_STATUS';
export const SAVE_USER_INFO = 'SAVE_USER_INFO';
